# Generated by Django 6.0.5 on 2026-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefuser',
            name='profile_icon',
            field=models.CharField(blank=True, choices=[('chef-default', "Chef's Hat"), ('spoon', 'Spoon'), ('pot', 'Pot'), ('flame', 'Flame'), ('dollar', 'Dollar Sign'), ('growth', 'Growth Arrow'), ('shield', 'Shield'), ('balance', 'Balance Scale'), ('star', 'Star'), ('chart', 'Chart')], default='chef-default', help_text='Avatar icon key (chef, spoon, pot, flame, dollar, growth, shield, etc.)', max_length=32),
        ),
        migrations.AddField(
            model_name='chefuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User selfie or profile photo', null=True, upload_to='profile_pictures/'),
        ),
    ]
