# Generated by Django 5.2.14 on 2026-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chefuser_profile_icon_chefuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenSeatCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_seat', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='chefuser',
            name='member_number',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Permanent, never-reused join position. Chef #1 is the first ever to join.', null=True, unique=True),
        ),
    ]
