# Generated by Django 6.0.5 on 2026-05-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_seed_required_modules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usermodulecompletion',
            new_name='acad_mod_pass_idx',
            old_name='academy_completion_user_pass_idx',
        ),
        migrations.RenameIndex(
            model_name='usermodulecompletion',
            new_name='acad_user_pass_idx',
            old_name='academy_completion_module_pass_idx',
        ),
    ]
