import {
  DashboardSnapshot,
  EXECUTION_MODE,
  Money,
} from "@/lib/types";

const zar = (amount: number): Money => ({
  amount,
  currency: "ZAR",
  precision: 2,
  mode: EXECUTION_MODE,
});

export const MOCK_MVP_DASHBOARD: DashboardSnapshot = {
  academyClearance: {
    complete: false,
    requiredModuleIds: ["markets-001", "risk-001"],
    passedModuleIds: ["markets-001"],
    missingModuleIds: ["risk-001"],
  },
  academyModules: [
    {
      id: "markets-001",
      title: "Market Basics",
      description: "How exchanges, indices, liquidity, and listed instruments behave before a Kitchen writes a recipe. The foundation every chef needs.",
      passed: true,
      locked: false,
      requiredForKitchen: true,
      estimatedMinutes: 24,
    },
    {
      id: "risk-001",
      title: "Risk and Return",
      description: "Position sizing, drawdown discipline, plate weight, and the 60% Rule before anyone cooks. The pot can be too hot.",
      passed: false,
      locked: false,
      requiredForKitchen: true,
      estimatedMinutes: 31,
    },
    {
      id: "portfolio-001",
      title: "Portfolio Construction",
      description: "Asset allocation, diversification theory, and how Kitchens build a balanced plate across sectors and time horizons.",
      passed: false,
      locked: true,
      requiredForKitchen: false,
      estimatedMinutes: 28,
    },
    {
      id: "bias-001",
      title: "Behavioural Biases",
      description: "Why smart chefs make irrational decisions — anchoring, overconfidence, herding, and the Kitchen's defence against them.",
      passed: false,
      locked: true,
      requiredForKitchen: false,
      estimatedMinutes: 22,
    },
    {
      id: "governance-001",
      title: "Kitchen Governance",
      description: "How recipes, votes, chefs at the table, and Gordon's review turn a thesis into a paper order the whole Kitchen can stand behind.",
      passed: false,
      locked: true,
      requiredForKitchen: false,
      estimatedMinutes: 28,
    },
    {
      id: "mutual-001",
      title: "Mutual Kitchen Mandate",
      description: "Slow cook, long game. Democratic governance with equal voting weight, diversified plates, and patient capital discipline.",
      passed: false,
      locked: true,
      requiredForKitchen: false,
      estimatedMinutes: 19,
    },
    {
      id: "hedge-001",
      title: "Hedge Kitchen Mandate",
      description: "High heat, strict rules. Asymmetric strategies, short exposure, risk-adjusted returns, and non-negotiable exit discipline.",
      passed: false,
      locked: true,
      requiredForKitchen: false,
      estimatedMinutes: 34,
    },
    {
      id: "ethics-001",
      title: "Market Conduct and Ethics",
      description: "Insider trading, market manipulation, disclosure obligations, and the ethical table every Young Investor must keep.",
      passed: false,
      locked: true,
      requiredForKitchen: false,
      estimatedMinutes: 26,
    },
    {
      id: "wealth-001",
      title: "Wealth-Creative Choice",
      description: "Four thinkers. One question: how does wealth actually get made? Abstract, iconic, and enactive — see it, map it, apply it.",
      passed: false,
      locked: false,
      requiredForKitchen: false,
      estimatedMinutes: 22,
    },
    {
      id: "wave-001",
      title: "Wave Literacy",
      description: "Markets move in five recognisable waves. Chefs who can name the wave they are riding make better, calmer, fewer decisions.",
      passed: false,
      locked: false,
      requiredForKitchen: false,
      estimatedMinutes: 19,
    },
  ],
  tradeProposals: [
    {
      id: "proposal-sbk-001",
      kitchenName: "UCT Alpha Kitchen",
      symbol: "SBK",
      assetName: "Standard Bank Group",
      proposedSide: "BUY",
      proposedUnits: 12,
      paperNotional: zar(2850),
      thesis: "A measured banking recipe: clean domestic-rate exposure, kept small enough for the Kitchen to digest without overloading the plate.",
      riskNote: "Critical heat: this plate pushes financials above the model limit. Gordon recommends reducing serving size before the table votes.",
      votes: {
        yes: 6,
        no: 3,
        abstain: 1,
        quorumRequired: 8,
        totalMembers: 12,
      },
      userVote: null,
      academyClearanceRequired: true,
      governanceModel: "mutual",
    },
    {
      id: "proposal-cpi-001",
      kitchenName: "Wits Compound Kitchen",
      symbol: "CPI",
      assetName: "Capitec Bank Holdings",
      proposedSide: "BUY",
      proposedUnits: 3,
      paperNotional: zar(6120),
      thesis: "Quality franchise, but the entry price needs patience and a narrow serving size. The table is still forming its view.",
      riskNote: "Gordon says wait for valuation heat to cool before the Kitchen adds more. This pot is warm but not reckless.",
      votes: {
        yes: 4,
        no: 4,
        abstain: 0,
        quorumRequired: 7,
        totalMembers: 10,
      },
      userVote: null,
      academyClearanceRequired: true,
      governanceModel: "mutual",
    },
    {
      id: "proposal-npn-001",
      kitchenName: "Rhodes Alpha Kitchen",
      symbol: "NPN",
      assetName: "Naspers Limited",
      proposedSide: "BUY",
      proposedUnits: 2,
      paperNotional: zar(7580),
      thesis: "Tencent discount thesis: Naspers trades below sum-of-parts. Small serving, long hold. The Kitchen is patient.",
      riskNote: "Concentration risk is manageable given Vault diversification. Gordon has no critical flag on this recipe.",
      votes: {
        yes: 9,
        no: 1,
        abstain: 2,
        quorumRequired: 10,
        totalMembers: 14,
      },
      userVote: null,
      academyClearanceRequired: true,
      governanceModel: "hedge",
    },
    {
      id: "proposal-mtn-001",
      kitchenName: "MSA Growth Kitchen",
      symbol: "MTN",
      assetName: "MTN Group",
      proposedSide: "SELL",
      proposedUnits: 30,
      paperNotional: zar(3480),
      thesis: "Trim the MTN plate. Currency risk across African operations is elevated. The Kitchen moves to reduce heat before the next reporting season.",
      riskNote: "Gordon agrees: reducing this position aligns with the Kitchen mandate. The pot was getting heavy.",
      votes: {
        yes: 7,
        no: 2,
        abstain: 1,
        quorumRequired: 8,
        totalMembers: 11,
      },
      userVote: null,
      academyClearanceRequired: true,
      governanceModel: "hedge",
    },
  ],
  portfolio: {
    totalSyndicateCapital: zar(48250),
    roiPercent: 8.4,
    holdings: [
      {
        symbol: "NPN",
        name: "Naspers",
        units: 5,
        paperValue: zar(18950),
        allocationPercent: 39.3,
        roiPercent: 11.2,
      },
      {
        symbol: "SBK",
        name: "Standard Bank Group",
        units: 44,
        paperValue: zar(9650),
        allocationPercent: 20.0,
        roiPercent: 5.7,
      },
      {
        symbol: "MTN",
        name: "MTN Group",
        units: 70,
        paperValue: zar(8120),
        allocationPercent: 16.8,
        roiPercent: -2.1,
      },
      {
        symbol: "SOL",
        name: "Sasol Limited",
        units: 18,
        paperValue: zar(5840),
        allocationPercent: 12.1,
        roiPercent: 3.4,
      },
      {
        symbol: "FSR",
        name: "FirstRand",
        units: 55,
        paperValue: zar(5690),
        allocationPercent: 11.8,
        roiPercent: 6.9,
      },
    ],
    sevenDayEquity: [
      { day: "D-6", value: 44500 },
      { day: "D-5", value: 45180 },
      { day: "D-4", value: 44940 },
      { day: "D-3", value: 46220 },
      { day: "D-2", value: 46880 },
      { day: "D-1", value: 47540 },
      { day: "NOW", value: 48250 },
    ],
    gordonMarketRead: {
      stance: "Measured heat, paper only",
      summary: "Momentum looks constructive but the Kitchen is leaning into financials. The next recipe needs a plate-weight check before it can be cleared.",
      riskScore: 72,
      criticalAlerts: [
        "Learn before you earn is incomplete for this user.",
        "This plate is too heavy in financials until Gordon reviews it.",
      ],
    },
  },
  timesFeature: {
    kicker: "Young Investor Times",
    title: "The 60% Rule Is Culture, Not Decoration",
    deck: "Why the table beats impulse, how Kitchens read missing chefs, and where Gordon blocks beautiful but reckless recipes.",
    byline: "Editorial desk / MOCK_MVP research note",
  },
  timesSecondary: [
    {
      kicker: "Governance",
      title: "Mutual vs Hedge: Two Ways to Run a Kitchen",
      deck: "The slow cook builds trust over time. The high-heat Kitchen demands discipline. Understanding which mandate suits your table is the first recipe every Kitchen must write.",
      byline: "Young Investors Academy / MOCK_MVP note",
    },
    {
      kicker: "Market Conduct",
      title: "Don't Be the Chef Who Tips the Table",
      deck: "Insider trading is not a grey area. The Young Investors Ethics module exists because every Kitchen needs a clean conscience before it cooks.",
      byline: "Compliance desk / MOCK_MVP note",
    },
  ],
  marketTickers: [
    { symbol: "J200",    name: "JSE Top 40",           price: zar(73120.55), changePercent:  0.8,  critical: false },
    { symbol: "NPN.JO",  name: "Naspers",               price: zar(3790.00),  changePercent:  1.4,  critical: false },
    { symbol: "PRX.JO",  name: "Prosus",                price: zar(1124.50),  changePercent:  0.9,  critical: false },
    { symbol: "MTN.JO",  name: "MTN Group",             price: zar(116.20),   changePercent: -1.6,  critical: false },
    { symbol: "SOL.JO",  name: "Sasol",                 price: zar(324.80),   changePercent: -0.7,  critical: false },
    { symbol: "ANG.JO",  name: "AngloGold Ashanti",     price: zar(714.00),   changePercent:  2.3,  critical: false },
    { symbol: "USDZAR",  name: "Dollar / Rand",         price: zar(18.37),    changePercent: -0.4,  critical: false },
    { symbol: "VIX",     name: "Volatility Watch",      price: zar(19.2),     changePercent:  6.3,  critical: true  },
  ],
  macroNews: [
    {
      id: "macro-001",
      region: "South Africa",
      headline: "Inflation print keeps rate-cut timing under review",
      summary: "Kitchens should avoid treating a single data point as a guaranteed catalyst for a new recipe.",
      critical: false,
    },
    {
      id: "macro-002",
      region: "Global",
      headline: "Critical alert: crowded plates are repricing fast",
      summary: "Gordon recommends smaller paper servings until market breadth improves across the JSE and emerging markets.",
      critical: true,
    },
    {
      id: "macro-003",
      region: "South Africa",
      headline: "Load-shedding eases — JSE energy sector watches closely",
      summary: "Improved energy stability is a tailwind for domestic industrials. Kitchens with SOL and AMS exposure may reconsider plate weight.",
      critical: false,
    },
  ],
  rankings: [
    {
      rank: 1,
      name: "Rhodes Test Kitchen",
      institution: "Rhodes University",
      paperCapital: zar(52100),
      roiPercent: 4.2,
      isGordon: false,
      beatGordon: true,
      earnedBadges: [
        { id: "first-service", name: "First Service", description: "Started your first Kitchen", category: "achievement" },
        { id: "risk-cleared", name: "Risk Cleared", description: "Completed Academy clearance", category: "clearance" },
        { id: "beat-gordon", name: "Beat Gordon", description: "Outperformed the benchmark", category: "achievement" },
      ],
    },
    {
      rank: 2,
      name: "Commerce House Pot",
      institution: "University of Cape Town",
      paperCapital: zar(49800),
      roiPercent: 3.8,
      isGordon: false,
      beatGordon: true,
    },
    {
      rank: 3,
      name: "Gordon",
      institution: "The Benchmark",
      paperCapital: zar(100000),
      roiPercent: 3.1,
      isGordon: true,
      beatGordon: false,
    },
    {
      rank: 4,
      name: "Late Night Traders",
      institution: "Wits University",
      paperCapital: zar(46200),
      roiPercent: 2.7,
      isGordon: false,
      beatGordon: false,
    },
    {
      rank: 5,
      name: "Eastern Cape Capital",
      institution: "Rhodes University",
      paperCapital: zar(43900),
      roiPercent: 1.4,
      isGordon: false,
      beatGordon: false,
    },
    {
      rank: 6,
      name: "MSA Growth Kitchen",
      institution: "MSA Academy",
      paperCapital: zar(40600),
      roiPercent: 1.1,
      isGordon: false,
      beatGordon: false,
    },
    {
      rank: 7,
      name: "Varsity Capital Kitchen",
      institution: "Varsity College",
      paperCapital: zar(39200),
      roiPercent: 0.8,
      isGordon: false,
      beatGordon: false,
    },
    {
      rank: 8,
      name: "The Grahamstown Table",
      institution: "Rhodes University",
      paperCapital: zar(34100),
      roiPercent: 0.3,
      isGordon: false,
      beatGordon: false,
    },
  ],
};
